# Generated by Django 5.1.15 on 2026-06-07 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardinstance',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_instances', to='collections.collection'),
        ),
        migrations.AddField(
            model_name='slot',
            name='parent_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='collections.slot'),
        ),
        migrations.AddField(
            model_name='cardinstance',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_instances', to='collections.slot'),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to='collections.collection'),
        ),
        migrations.AddField(
            model_name='slot',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='collections.storageunit'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'name')},
        ),
    ]
